### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [6]:
import numpy as np
import random as rd

In [7]:
arr = np.random.randint(1, 21, size=(5,5))
print(arr)

[[17 15 13  5  5]
 [ 6  9 13 18 13]
 [11  5  9  3 19]
 [ 6 12 13  7  1]
 [20  4 14 10  6]]


In [8]:
arr[2] = np.ones(shape=(1,5))
arr

array([[17, 15, 13,  5,  5],
       [ 6,  9, 13, 18, 13],
       [ 1,  1,  1,  1,  1],
       [ 6, 12, 13,  7,  1],
       [20,  4, 14, 10,  6]], dtype=int32)

In [15]:
# 2
arr = np.arange(1,17).reshape((4,4))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
np.fill_diagonal(arr, 1)
arr

array([[ 1,  2,  3,  4],
       [ 5,  1,  7,  8],
       [ 9, 10,  1, 12],
       [13, 14, 15,  1]])

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [21]:
arr = np.arange(1,37).reshape((6,6))
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [22]:
arr3to5 = arr[3:6]
arr3to5

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [23]:
arr2to4 = arr[2:5]
arr2to4

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [26]:
arr = np.random.randint(1, 21, size=(5,5))
arr

array([[11, 11,  1, 13, 18],
       [ 1, 13,  2, 17, 18],
       [14, 14,  5,  3, 19],
       [ 1,  2, 18, 16,  2],
       [17,  3, 18, 15,  3]], dtype=int32)

In [31]:
border = np.concatenate((arr[0, : ], arr[-1, : ],arr[1:-1, 0], arr[1:-1, -1]))
border

array([11, 11,  1, 13, 18, 17,  3, 18, 15,  3,  1, 14,  1, 18, 19,  2],
      dtype=int32)

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [36]:
arr1, arr2 = np.random.randint(1,13,size=(3,4)), np.random.randint(1,13,size=(3,4))
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[ 7 17 14 16]
 [17 14 14 14]
 [ 3  8  2 17]]
[[ -5  -1 -10  -4]
 [ -3   0  -6  10]
 [ -1   6   0  -3]]
[[ 6 72 24 60]
 [70 49 40 24]
 [ 2  7  1 70]]
[[0.16666667 0.88888889 0.16666667 0.6       ]
 [0.7        1.         0.4        6.        ]
 [0.5        7.         1.         0.7       ]]


In [46]:
arr = np.arange(1,17).reshape(4,4)
print(np.sum(arr,axis=0)) # column
print(np.sum(arr,axis=1)) # row

[28 32 36 40]
[10 26 42 58]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [51]:
arr = np.random.randint(1,26, size=(5,5))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

14.04
16.0
6.690171896147363
44.7584


In [58]:
arr = np.arange(1,10).reshape(3,3)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

5.0
5.0
2.581988897471611
6.666666666666667


In [65]:
normalized = (arr - np.mean(arr)) / np.std(arr)
print(np.std(normalized))
print(np.mean(normalized))

1.0
0.0


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [77]:
arr = np.random.randint(1,11,size=(3,3))
new_row = np.random.randint(1,11,size = (3,))
print(arr)
print(new_row)

[[10  6  1]
 [ 6  8  3]
 [ 7  4  3]]
[6 1 1]


In [78]:
result = arr + new_row
result

array([[16,  7,  2],
       [12,  9,  4],
       [13,  5,  4]], dtype=int32)

In [79]:
new_column = np.random.randint(1,11,size=(3,1))
new_column

array([[6],
       [9],
       [4]], dtype=int32)

In [80]:
result2 = arr + new_column
result2

array([[16, 12,  7],
       [15, 17, 12],
       [11,  8,  7]], dtype=int32)

In [83]:
# another way:
new_row = new_row[:, np.newaxis]
new_row

array([[6],
       [1],
       [1]], dtype=int32)

In [84]:
arr + new_row

array([[16, 12,  7],
       [ 7,  9,  4],
       [ 8,  5,  4]], dtype=int32)