## Numpy

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrics, along with a collection of mathe matical functions to operate on these data structures. In this lesson, we will cover the basics of Numpy, focusing on arrays and vectorized operations.

In [2]:
!pip install numpy

In [3]:
import numpy as np

## Create arrays using numpy
## 1D

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2.shape)
print(arr2)
print("--------")
print(arr2.T)


(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
--------
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
arr = np.array([[1,2,3.1],[4,5,6]])

print(arr) # print array
print(arr.shape) #print shape (2,3)
print(arr.ndim) #print dimention count (2)
print(arr.size) # print size 6
print(arr.dtype) #print type of data: float64 (base on OS in use)
print(arr.itemsize) #print item size (in bytes)

[[1.  2.  3.1]
 [4.  5.  6. ]]
(2, 3)
2
6
float64
8


In [9]:
## Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#Element Wise Addition
print("Addition: ", arr1 + arr2)
print("Subtraction: ", arr1 - arr2)
print("Multiplication: ", arr1 * arr2)
print("Division: ", arr1 / arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [10]:
arr = np.array([1,2,3])
print(np.sqrt(arr))
print(np.log10(arr))
print(np.sin(arr))

[1.         1.41421356 1.73205081]
[0.         0.30103    0.47712125]
[0.84147098 0.90929743 0.14112001]


In [11]:
## Array slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
arr[0][1]

np.int64(2)

In [13]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [15]:
## Modify array elements
arr[0,0] = 100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [ ]:
## Statistical concepts -- Normalization
## To have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean: (1+2+3+...+10)/10
mean = np.mean(data)
print("Mean:", mean)

# Median: Trung binh cong 2 so o giua: (5+6)/2
median = np.median(data)
print("Median:", median)

# Standard deviation: [SUM(x_i-mean)^2]/2
std_dev = np.std(data)
print("Standard deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25


In [20]:
# Normalization: to have a mean of 0 and standard deviation of 1
print(data - np.mean(data))

[-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]


In [24]:
arr2 = data - np.mean(data)
arr2 /= np.std(data)
print(arr2)
print(np.std(arr2))

[-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]
1.0
